# 3. Index
데이터에 접근할 수 있는 주소 값

In [1]:
import pandas as pd

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}
df = pd.DataFrame(data, index=['1', '2', '3', '4', '5', '6', '7', '8'])
df

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
1  채치수  북산고  197   90   85  100  95  85      Python
2  정대만  북산고  184   40   35   50  55  25        Java
3  송태섭  북산고  168   80   75   70  80  75  Javascript
4  서태웅  북산고  187   40   60   70  75  80
5  강백호  북산고  188   15   20   10  35  10
6  변덕규  능남고  202   80  100   95  85  80           C
7  황태산  능남고  188   55   65   45  40  35      PYTHON
8  윤대협  능남고  190  100   85   90  95  95          C#

In [2]:
df.index

Index(['1', '2', '3', '4', '5', '6', '7', '8'], dtype='str')

## Index 이름 설정

In [3]:
df.index.name = '지원번호' # index의 이름 설정
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1     채치수  북산고  197   90   85  100  95  85      Python
2     정대만  북산고  184   40   35   50  55  25        Java
3     송태섭  북산고  168   80   75   70  80  75  Javascript
4     서태웅  북산고  187   40   60   70  75  80
5     강백호  북산고  188   15   20   10  35  10
6     변덕규  능남고  202   80  100   95  85  80           C
7     황태산  능남고  188   55   65   45  40  35      PYTHON
8     윤대협  능남고  190  100   85   90  95  95          C#

## Index 초기화

In [4]:
df.reset_index()

  지원번호   이름   학교    키   국어   영어   수학  과학  사회        SW특기
0    1  채치수  북산고  197   90   85  100  95  85      Python
1    2  정대만  북산고  184   40   35   50  55  25        Java
2    3  송태섭  북산고  168   80   75   70  80  75  Javascript
3    4  서태웅  북산고  187   40   60   70  75  80
4    5  강백호  북산고  188   15   20   10  35  10
5    6  변덕규  능남고  202   80  100   95  85  80           C
6    7  황태산  능남고  188   55   65   45  40  35      PYTHON
7    8  윤대협  능남고  190  100   85   90  95  95          C#

In [12]:
df.reset_index(drop=True) # 원래 쓰던 '지원번호' 인덱스 삭제

    학교    키   국어   영어   수학  과학  사회        SW특기
0  북산고  197   90   85  100  95  85      Python
1  북산고  184   40   35   50  55  25        Java
2  북산고  168   80   75   70  80  75  Javascript
3  북산고  187   40   60   70  75  80
4  북산고  188   15   20   10  35  10
5  능남고  202   80  100   95  85  80           C
6  능남고  188   55   65   45  40  35      PYTHON
7  능남고  190  100   85   90  95  95          C#

In [13]:
df.reset_index(drop=True, inplace=True) # 실제 데이터에 바로 반영
df

    학교    키   국어   영어   수학  과학  사회        SW특기
0  북산고  197   90   85  100  95  85      Python
1  북산고  184   40   35   50  55  25        Java
2  북산고  168   80   75   70  80  75  Javascript
3  북산고  187   40   60   70  75  80
4  북산고  188   15   20   10  35  10
5  능남고  202   80  100   95  85  80           C
6  능남고  188   55   65   45  40  35      PYTHON
7  능남고  190  100   85   90  95  95          C#

## Index 설정
지정한 col로 Index를 설정

In [20]:
df.set_index('이름', inplace=True)
df

KeyError: "None of ['이름'] are in the columns"

## Index 정렬
Index를 기준으로 오름차순, 내림차순 정렬

In [22]:
df.sort_index() # 인덱스로 오름차순 정렬

    학교    키   국어   영어   수학  과학  사회        SW특기
0  북산고  197   90   85  100  95  85      Python
1  북산고  184   40   35   50  55  25        Java
2  북산고  168   80   75   70  80  75  Javascript
3  북산고  187   40   60   70  75  80
4  북산고  188   15   20   10  35  10
5  능남고  202   80  100   95  85  80           C
6  능남고  188   55   65   45  40  35      PYTHON
7  능남고  190  100   85   90  95  95          C#

In [ ]:
df.sort_index(ascending=False) # 내림차순 정렬

    학교    키   국어   영어   수학  과학  사회        SW특기
7  능남고  190  100   85   90  95  95          C#
6  능남고  188   55   65   45  40  35      PYTHON
5  능남고  202   80  100   95  85  80           C
4  북산고  188   15   20   10  35  10
3  북산고  187   40   60   70  75  80
2  북산고  168   80   75   70  80  75  Javascript
1  북산고  184   40   35   50  55  25        Java
0  북산고  197   90   85  100  95  85      Python